# Generated by Django 5.2.12 on 2026-03-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_pestpredictionmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pestpredictionmodel',
            name='eco_solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pestpredictionmodel',
            name='harmful_percentage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
